export const GET_ALL_TYPE_FOOD_SUCCESS = 'GET_ALL_TYPE_FOOD_SUCCESS';
export const GET_ALL_TYPE_FOOD_FAILURE = 'GET_ALL_TYPE_FOOD_FAILURE';

export const GET_FOOD_BY_TYPE_SUCCESS = 'GET_FOOD_BY_TYPE_SUCCESS';
export const GET_FOOD_BY_TYPE_FAILURE = 'GET_FOOD_BY_TYPE_FAILURE';

export const SEARCH_FOOD_SUCCESS = 'SEARCH_FOOD_SUCCESS';
