export const GET_ALL_TYPE_FOOD_SUCCESS = 'GET_ALL_TYPE_FOOD_SUCCESS';
export const GET_ALL_TYPE_FOOD_FAILURE = 'GET_ALL_TYPE_FOOD_FAILURE';

export const GET_ALL_FOOD_SUCCESS = 'GET_ALL_FOOD_SUCCESS';
export const GET_ALL_FOOD_FAILURE = 'GET_ALL_FOOD_FAILURE';
