export const COLOR = {
  WHITE_COLOR: '#FFFFFF',
  BLACK_COLOR: '#000000',
  TEXT_SECONDARY_COLOR: '#777777',
  BORDER_COLOR: '#9fa0a4',
  GREEN_COLOR: '#44db5e',
};

export default {
  BORDER_RADIUS: 8,
  BORDER_RADIUS_SMALL: 4,

  FONT_SIZE_SMALL: 12,
  FONT_SIZE_NORMAL: 14,
  FONT_SIZE_MEDIUM: 16,
  FONT_SIZE_LARGE: 18,

  PADDING_SMALL: 8,
  PADDING_NORMAL: 12,
  PADDING_LARGE: 20,

  MARGIN_SMALL: 10,
  MARGIN_NORMAL: 20,
  MARGIN_LARGE: 40,

  COLOR,
};
